name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dev dependencies
      run: sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev
    - uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: '1.17.x'
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
